[project]
name = "system-forecast-do-an"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evdev>=1.9.2",
    "psutil>=7.2.1",
]
